# Generated by Django 4.1 on 2025-04-09 06:15

import bson.objectid
from django.db import migrations
import djongo.models.fields


# Adjust the migration to avoid unsupported operations by djongo
class Migration(migrations.Migration):

    dependencies = [
        ("octofit_tracker", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="id",
        ),
        # Instead of adding an ObjectIdField, we will keep the default id field
        # or handle this change manually in the database if necessary.
    ]
